# Generated by Django 6.0.2 on 2026-04-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_avatar_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='vin',
            field=models.CharField(blank=True, default='', max_length=17),
        ),
    ]
